### ISSUE TITLE
Cannot run in rpi 3

### ISSUE THREAD

**Issue by DanielRamosAcosta** [LukeChannings/docker-deno#1]
I'm running docker with the hypriot image in my Raspberry pi. I'm having the following error:

```
$ docker run lukechannings/deno --help
Unable to find image 'lukechannings/deno:latest' locally
latest: Pulling from lukechannings/deno
docker: no matching manifest for linux/arm/v7 in the manifest list entries.
See 'docker run --help'
```

This is my docker version:

```
$ docker --version
Docker version 20.10.7, build f0df350
```

I'm not sure if the image you are providing allow us to run deno in a rpi

**Comment by LukeChannings** [comment]
You’re running a 32-bit distribution, there is only a 64-but ARM image available sadly. 

You can install a 64-bit distribution on the Pi 3, which is what I’d suggest.

**Comment by DanielRamosAcosta** [comment]
I don't know why I'm running the 32bit version, thanks!
