### ISSUE TITLE
Update container base images

### ISSUE THREAD

**Issue by EdJoPaTo** [LukeChannings/docker-deno#10]
Thanks for your efforts in providing arm64 binaries of deno! Its awesome to have the option to use them.

Currently the container base images in use are `ubuntu:16.04` and `ubuntu:20.04` which is kinda old. I know that [16.04 still receives extended security support](https://ubuntu.com/about/release-cycle) but updating to 22.04 might seem wise?

While looking into the Dockerfiles I noted some other things:

The compile image also tries to install python which was python2 back then. I'm not even sure where its used as its not referenced anywhere (`rg python` is empty). It should be replaced by python3 or removed when not used.

Also `/bin` is a symlink to `/usr/bin` so maybe use `/usr/bin` directly in ENTRYPOINT and COPY places. Maybe even use `/usr/local/bin` as stuff not managed by the package manager is normally placed there. But that might be a breaking change for some? (denoland/deno uses `/usr/bin/deno` and `/usr/local/bin/docker-entrypoint.sh`. Not sure why they use both locations.)

Feel free to follow or ignore my suggestions. I can also create a PR to implement some/all but I want to discuss them first and cant really test them myself so I went for creating an issue. Thanks again for your efforts!

**Comment by LukeChannings** [comment]
`ubuntu:16.04` was chosen specifically to support the oldest glibc possible. `ubuntu:20.04` is still in its prime LTS time.

**Comment by EdJoPaTo** [comment]
Ah, thanks for clarifying with the glibc version!

My other points mentioned might be interesting to consider but as this repo is mostly about the binary they might not be as relevant here. Personally I am now using my own images with the precompiled binary and moved on.

Thanks again for your efforts of providing the precompiled binaries!
