### ISSUE TITLE
Can Only run one Bot at a time

### ISSUE THREAD

**Issue by ghost** [LukeChannings/docker-deno#12]
Hello...

I find this project interesting, but i seem to be having an issue...
See, i Host Discord Bots for Servers, and i decided to move over to Oracle Cloud, which involved me using Ampere (or the ARM architecture), so i found this project.

The issue im having is, when i run more than one bot at a time, every bot, except for the one i started first, dies. I have no idea if this is a limitation with this project, or if its Oracle, but ive been having this issue since yesterday

**Comment by LukeChannings** [comment]
This sounds like it's unrelated to this project - can you reproduce the architecture in x86 and reproduce the problem?

This project simply compiles Deno for aarch64.
