### ISSUE TITLE
v1.31.2 contains old version

### ISSUE THREAD

**Issue by simon--taylor** [LukeChannings/docker-deno#15]
The v1.31.2 release binary says it is v1.31.1.
```
> curl -LOs https://github.com/LukeChannings/deno-arm64/releases/download/v1.31.2/deno-linux-arm64.zip
> unzip -q deno-linux-arm64.zip
> ./deno --version
deno 1.31.1 (release, aarch64-unknown-linux-gnu)
v8 11.0.226.19
typescript 4.9.4
```

**Comment by LukeChannings** [comment]
Hey, sorry!

This is the first time the fully automated builds have run, and it looks like I missed a misconfiguration in the Github Action that kicks off the build - it was using the repo's github ref, which is usually the version tag, but the new process runs the workflow from the main branch.

I've corrected that, and re-run the job. Future builds should be fully automatic, and this one will be finished in about 20 minutes.
