### ISSUE TITLE
Deno can't run on Snapdragon 865 Android phone?

### ISSUE THREAD

**Issue by masx200** [LukeChannings/docker-deno#19]
Deno can't run on Snapdragon 865 Android phone?

The operating environment is zerotermux

Linux localhost 4.19.157-perf-g4388af90b0da #1 SMP PREEMPT Wed Mar 1 21:53:21 CST 2023 aarch64 Android

~ $ ls ./deno -l
-rwxrwxrwx 1 u0_a26 u0_a26 104878816 May  5 00:55 ./deno

~ $ ./deno
bash: ./deno: No such file or directory

$ sha1sum deno
0e9a4200206216fd6c94f1ecde39ddc958c16b47  deno

**Comment by LukeChannings** [comment]
This’ll be a glibc issue. Android doesn’t use glibc, it uses [Bionic](https://en.m.wikipedia.org/wiki/Bionic_(software)). If you want to run on Android you’ll have to either install full glibc or find a Deno build for Android.

**Comment by masx200** [comment]
Can I statically link GLIbC to Deno's binary?

Or how do I install glibc on Android?
