### ISSUE TITLE
Deno not properly install on raspberrypi os

### ISSUE THREAD

**Issue by DNAScanner** [LukeChannings/docker-deno#21]
After installing the installation script found on this repos readme, deno is not properly installed and cannot be executed. CPU architecture is aarch64
![image](https://github.com/LukeChannings/deno-arm64/assets/75182303/1bd9d5ea-b15b-43f0-957a-d533dce8eac6)

**Comment by LukeChannings** [comment]
<img width="1202" alt="Screenshot 2023-08-14 at 19 26 30" src="https://github.com/LukeChannings/deno-arm64/assets/461449/172fe736-091c-400d-b2b8-4bb4edc0176d">

Which version of PiOS are you using, and what's the output of `ld --version`?

For the latest release I needed to upgrade my build version because of https://github.com/denoland/deno/issues/20131, this could be related.

If you download version [v1.36.0](https://github.com/LukeChannings/deno-arm64/releases/tag/v1.36.0) does it also error?

```
curl -OL https://github.com/LukeChannings/deno-arm64/releases/download/v1.36.0/deno-linux-arm64.zip
unzip deno-linux-arm64.zip
./deno --version
```

**Comment by DNAScanner** [comment]
The current version of pios is `2.35.2` (`GNU ld (GNU Binutils for Raspbian) 2.35.2`). After executing the code you sent, im still getting the same error
![image](https://github.com/LukeChannings/deno-arm64/assets/75182303/4ba21084-d243-4f94-a12b-990e870f1391)

**Comment by LukeChannings** [comment]
Well it's good it's not a libc version problem, but now we have to do diagnostics 😆.

I guess the first thing is to make sure it's executable with `chmod +x ./deno`, and try to run it again. Seems unlikely to be the problem though.

- Exact version of Raspberry Pi OS, as well as a link to the image you're using? 
- Output of `uname -a`
- Output of `file deno`
- Output of `ls -al /lib/ld-linux-aarch64.so.1`
- Any other diagnostics you think might be useful.

**Comment by DNAScanner** [comment]
For installing the os, i just used the raspberrypi imager (on windows), which automatically gets the most recent rpi os image afaik. I installed the image about a year ago.

`uname -a` output:
![image](https://github.com/LukeChannings/deno-arm64/assets/75182303/4177c948-634c-462c-85c2-350a96ffec97)

`file deno` output:
![image](https://github.com/LukeChannings/deno-arm64/assets/75182303/77e722ab-9de3-42b3-bd7b-55effa4c32c2)

`ls -al /lib/ld-linux-aarch64.so.1` output:
![image](https://github.com/LukeChannings/deno-arm64/assets/75182303/69b6698b-381f-4d92-8252-2ef4c502bf1c)

**Comment by LukeChannings** [comment]
Hmm, looks like you don't have a 64-bit libc installed. Earlier 64-bit Raspberry Pi OS might have a 64-bit kernel but a 32-bit userland, so you can't run 64-bit binaries.

What's the output of `dpkg-architecture --list`?

**Comment by DNAScanner** [comment]
```shell
pi@dnarpi:~/Desktop $ dpkg-architecture --list
DEB_BUILD_ARCH=armhf
DEB_BUILD_ARCH_ABI=eabihf
DEB_BUILD_ARCH_BITS=32
DEB_BUILD_ARCH_CPU=arm
DEB_BUILD_ARCH_ENDIAN=little
DEB_BUILD_ARCH_LIBC=gnu
DEB_BUILD_ARCH_OS=linux
DEB_BUILD_GNU_CPU=arm
DEB_BUILD_GNU_SYSTEM=linux-gnueabihf
DEB_BUILD_GNU_TYPE=arm-linux-gnueabihf
DEB_BUILD_MULTIARCH=arm-linux-gnueabihf
DEB_HOST_ARCH=armhf
DEB_HOST_ARCH_ABI=eabihf
DEB_HOST_ARCH_BITS=32
DEB_HOST_ARCH_CPU=arm
DEB_HOST_ARCH_ENDIAN=little
DEB_HOST_ARCH_LIBC=gnu
DEB_HOST_ARCH_OS=linux
DEB_HOST_GNU_CPU=arm
DEB_HOST_GNU_SYSTEM=linux-gnueabihf
DEB_HOST_GNU_TYPE=arm-linux-gnueabihf
DEB_HOST_MULTIARCH=arm-linux-gnueabihf
DEB_TARGET_ARCH=armhf
DEB_TARGET_ARCH_ABI=eabihf
DEB_TARGET_ARCH_BITS=32
DEB_TARGET_ARCH_CPU=arm
DEB_TARGET_ARCH_ENDIAN=little
DEB_TARGET_ARCH_LIBC=gnu
DEB_TARGET_ARCH_OS=linux
DEB_TARGET_GNU_CPU=arm
DEB_TARGET_GNU_SYSTEM=linux-gnueabihf
DEB_TARGET_GNU_TYPE=arm-linux-gnueabihf
DEB_TARGET_MULTIARCH=arm-linux-gnueabihf
```

**Comment by LukeChannings** [comment]
Yeah, looks like you have a 32-bit userland, which means any 64-bit arm binary will not run, not just my Deno builds.

Installing the latest Raspberry Pi OS should fix this. You might also be able to do a full upgrade with apt, but I'm not sure.
