### ISSUE TITLE
failed to `docker container run`

### ISSUE THREAD

**Issue by ghost** [LukeChannings/docker-deno#23]
I ran `docker container run --rm -it lukechannings/deno:latest`, but an error occurred. The error was `Module not found "https://deno.land/std/examples/welcome.ts".`.

I accessed `https://deno.land/std/examples/welcome.ts`, but `welcome.ts` was not found. So, it might be better to modify [this line](https://github.com/LukeChannings/deno-arm64/blob/main/Dockerfile#L30).

Thanks !

**Comment by LukeChannings** [comment]
Looks like all of the examples were deleted in Standard Library 0.199.0 (maybe too much of a maintenance burden?).
I've pointed it to version 0.198.0.
