### ISSUE TITLE
Not working for Termux

### ISSUE THREAD

**Issue by J053Fabi0** [LukeChannings/docker-deno#25]
`deno` outputs this: 

```
exec: Failed to execute process '/data/data/com.termux/files/home/.deno/bin/deno': The file exists and is executable. Check the interpreter or linker?
```

Only when I use [Arch Linux inside Termux](https://github.com/SDRausty/TermuxArch) it works. It's the same binary that works for Arch Linux but not for Termux.

**Comment by LukeChannings** [comment]
I don't use Termux but assume this is because the environment doesn't have glibc. See also #19.

I don't plan on producing MUSL builds, so I'll close this. Feel free to reply if you think I'm wrong and I'll re-open.
