### ISSUE TITLE
v1.40.5 doesn't have the binary asset

### ISSUE THREAD

**Issue by marc-barry** [LukeChannings/docker-deno#26]
https://github.com/LukeChannings/deno-arm64/releases/tag/v1.40.5 doesn't have the binary asset (i.e. like https://github.com/LukeChannings/deno-arm64/releases/download/v1.40.4/deno-linux-arm64.zip).

**Comment by LukeChannings** [comment]
Yep, you can now get the binary from the official Deno repo - https://github.com/denoland/deno/releases/tag/v1.40.5.

If you run `deno upgrade` and you were on v1.40.4 you will automatically be changed over to the official Deno binaries.

**Comment by marc-barry** [comment]
Thanks for this project. It has really helped us. I wasn't aware that they now support `arm64`. I guess I missed it in one of the release notes.

**Comment by marc-barry** [comment]
Ahh. Found it: https://github.com/denoland/deno/pull/22298
