### ISSUE TITLE
Raspberry Pi - deno/land doesn't support and this repo is not supported

### ISSUE THREAD

**Issue by tsaxking** [LukeChannings/docker-deno#27]
Hello, I recognize that this package has been essentially deprecated because Deno has supported arm64 now. However, I am trying to install Deno on a raspberry pi 4, and now I'm unable to since no installation is working (deno, cargo, snap, etc.) and this has been removed.

I'm unsure if snap just hasn't updated its servers yet, would it be possible to keep the builds available until everything updates?

**Comment by LukeChannings** [comment]
Hey @tsaxking,

I'm surprised that the official releases wouldn't run if my build did. I have tested the official builds on Ubuntu 20.04 and Debian 11 (bullseye), both running on Raspberry Pi 4.

Please make sure:

1. You're running a 64-bit distribution
2. You're using the latest available distribution

Thanks!

**Comment by tsaxking** [comment]
Thanks for the response @LukeChannings, I checked os and distribution and it's running ubuntu 20.4.5 on aarch64. I'm afraid I don't know much beyond that point. Is my pi incompatible with deno right now?

**Comment by tsaxking** [comment]
Alright, I had to do it the hard way using wget and manually installing. For some reason, cargo/snap/nix-shell/asdf were not working for various reasons.

For those who are stuck, like me:
`wget https://github.com/denoland/deno/releases/download/v1.40.5/deno-aarch64-unknown-linux-gnu.zip`
`unzip deno-aarch64-unknown-linux-gnu.zip`
`sudo cp deno /usr/local/bin/deno`

Then it should work. Apologies for raising an issue, and thank you for your help!
