### ISSUE TITLE
Local compile error

### ISSUE THREAD

**Issue by rossholdway** [LukeChannings/docker-deno#4]
Hi,

This is great, thank you. Out of interest (and I'm no expert in Rust / the build process) if I clone the repo and run the build command on an M1 Mac the process fails at the end. Am I missing something?

`docker build -t deno-build --build-arg DENO_VERSION=v1.21.2 --file ./Dockerfile.compile .` 

```
...
error: could not compile `deno_runtime`

Caused by:
  process didn't exit successfully: `CARGO=/root/.rustup/toolchains/1.59.0-aarch64-unknown-linux-gnu/bin/cargo
...
```

**Comment by LukeChannings** [comment]
Hey Ross,

It is a bit complicated, but I think what happens is `docker build` on M1 macs will compile for x86_64 by default, or something to that effect.

I use: `docker buildx build -t deno-build --platform=linux/arm64 -o type=docker --build-arg DENO_VERSION=v1.21.2 --file ./Dockerfile.compile .` The deno binary will then be in `/deno/target/release/deno` in the generated image.

To extract it, I use: `docker run --rm -v $(pwd):/pwd deno-build cp /deno/target/release/deno /pwd/`.

If you need an image with the compiled deno build, you can use: `docker buildx build -t deno --platform=linux/arm64 -o type=docker --file ./Dockerfile.standalone .`

I think... I haven't actually tested these in a while 😉.

Note: you may need to run `docker buildx create --use` first.

**Comment by rossholdway** [comment]
Thanks for the suggestions @LukeChannings. Unfortunately it's the same outcome. Not sure what's causing it as the output just seems to reference that the process didn't exist successfully so I don't have much to go on!

**Comment by rossholdway** [comment]
Just to provide an update, removing `--all-targets`, so just `cargo build --release --locked` outputs a valid build of deno 🎉 

Unfortunately, I'm not 100% sure of the full impact of excluding the `--all-targets` flag, or why I need to remove it for the build to succeed in my instance.
