### ISSUE TITLE
Advice on download script

### ISSUE THREAD

**Issue by tracker1** [LukeChannings/docker-deno#9]
I'm currently using the following as a script that gets called inside my container... open to suggestions.

Aside: really wish there was an easier way to download the *latest* release...  Added `$GITHUB_TOKEN` header because I was bumping up against api request limits when testing.

```bash
#! /bin/bash

cd /tmp

ARCH=$(uname -m)
VERSION=$(curl --header "authorization: Bearer $GITHUB_TOKEN" -s https://api.github.com/repos/LukeChannings/deno-arm64/releases/latest | grep "tag_name" | cut -d : -f 2 | tr -d \"\,[:space:])

echo ""
echo "Retrieving Deno: $VERSION $ARCH"

# linux/amd64 --- -Lsf
[ "$ARCH" == "x86_64" ] && curl -Lsf "https://github.com/denoland/deno/releases/download/$VERSION/deno-x86_64-unknown-linux-gnu.zip" -o deno.zip || true

# linux/arm64
[ "$ARCH" == "aarch64" ] && curl -Lsf "https://github.com/LukeChannings/deno-arm64/releases/download/$VERSION/deno-linux-arm64.zip" -o deno.zip || true

# extract deno.zip to /usr/local/bin/deno
[ -f "deno.zip" ] && unzip deno.zip && rm deno.zip && mv deno /usr/local/bin/deno

```

**Comment by LukeChannings** [comment]
You can download the latest artefact using:

```
curl -L https://github.com/LukeChannings/deno-arm64/releases/latest/download/deno-linux-arm64.zip -o deno.zip
```

**Comment by LukeChannings** [comment]
Here's a universal install script I knocked together by modifying the official Deno install.sh:

[deno_install.sh](https://gist.github.com/LukeChannings/09d53f5c364391042186518c8598b85e#file-deno_install-sh)

Usage:

```
curl https://gist.githubusercontent.com/LukeChannings/09d53f5c364391042186518c8598b85e/raw/ac8cd8c675b985edd4b3e16df63ffef14d1f0e24/deno_install.sh | sh
```

I don't recommend piping anything to `sh` unless you have read the source.

**Comment by tracker1** [comment]
@LukeChannings thanks... looks decent, will modify my loader when I get a chance.
